name: Airshipper

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-12

    steps:
    - name: Build Homebrew bottle
      run: |
        brew install --build-bottle --verbose printfn/custom-tap/airshipper
        brew bottle --no-rebuild printfn/custom-tap/airshipper
        zip airshipper-bottle.zip airshipper*
    - name: Upload bottle
      uses: actions/upload-artifact@v2.3.1
      with:
        name: airshipper-bottle
        path: airshipper-bottle.zip
        if-no-files-found: error
