name: armagetronad

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-12

    steps:
    - name: Build Homebrew bottle
      run: |
        brew install --build-bottle --verbose printfn/custom-tap/armagetronad
        brew bottle --no-rebuild printfn/custom-tap/armagetronad
    - name: Upload bottle
      uses: actions/upload-artifact@v2.3.1
      with:
        name: armagetronad-bottle
        path: armagetronad-*.bottle.tar.gz
        if-no-files-found: error
